language: python
python: 2.7
os:
  - linux

script:
 - src/prepare_asaim/launch_galaxy.sh  
 - src/prepare_asaim/populate_galaxy.sh
 - src/prepare_asaim/prepare_databases.sh

notifications:
  email: false
