sudo: required
language: minimal
python: 2.7

services:
  - docker

env:
  matrix:
  - TOX_ENV=py27

before_install:
  - wget https://raw.githubusercontent.com/galaxyproject/galaxy-flavor-testing/d443915a43f3632708afbcdb1e97a7adaf5b5c77/Makefile
  - make docker_install
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev
  - travis_wait 75 make docker_build
  - make docker_run
  - sleep 60

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend