---

api_key: admin
galaxy_instance: http://localhost:8080
tools:

# data_retrieval
- name: 'suite_ebi_tools'
  owner: 'iuc'
  tool_panel_section_label: 'data_retrieval'
  
- name: 'suite_enasearch'
  owner: 'iuc'
  tool_panel_section_label: 'data_retrieval'

- name: 'suite_ncbi_entrez'
  owner: 'iuc'
  tool_panel_section_label: 'data_retrieval'

- name: 'sra_tools'
  owner: 'iuc'
  tool_panel_section_label: 'data_retrieval'

# text_manipulation 
- name: 'add_value'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'change_case'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'column_join'
  owner: 'jjohnson'
  tool_panel_section_label: 'text_manipulation'

- name: 'collection_column_join'
  owner: 'iuc'
  tool_panel_section_label: 'text_manipulation'

- name: 'column_maker'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'concatenate_multiple_datasets'
  owner: 'mvdbeek'
  tool_panel_section_label: 'text_manipulation'

- name: 'convert_characters'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'cut_columns'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'merge_cols'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'regex_find_replace'
  owner: 'galaxyp'
  tool_panel_section_label: 'text_manipulation'

- name: 'remove_beginning'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'show_beginning'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'show_tail'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'split_file_on_column'
  owner: 'bgruening'
  tool_panel_section_label: 'text_manipulation'

- name: 'unique'
  owner: 'bgruening'
  tool_panel_section_label: 'text_manipulation'

- name: 'normalize_dataset'
  owner: 'bebatut'
  tool_panel_section_label: 'text_manipulation'

- name: 'extract_min_max_lines'
  owner: 'bebatut'
  tool_panel_section_label: 'text_manipulation'

- name: 'text_processing'
  owner: 'bgruening'
  tool_panel_section_label: 'text_manipulation'

- name: 'suite_datamash'
  owner: 'iuc'
  tool_panel_section_label: 'text_manipulation'

# seq_manipulation 
- name: 'seq_filter_by_id'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'seq_rename'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'seq_select_by_id'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fastq_to_fasta'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fasta_to_tabular'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'split_paired_reads'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'convert_extract_sequence_file'
  owner: 'bebatut'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fasta_add_barcode'
  owner: 'bebatut'
  tool_panel_section_label: 'seq_manipulation'
 
- name: 'fastq_combiner'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_filter'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fastq_groomer'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_manipulation'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_masker_by_quality'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_paired_end_deinterlacer'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_paired_end_interlacer'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_paired_end_joiner'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_paired_end_splitter'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_stats'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_to_tabular'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastq_trimmer'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'fastqtofasta'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'
  
- name: 'tabular_to_fastq'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'   
 
# bam_sam_manipulation
- name: 'suite_samtools_1_2'
  owner: 'devteam'
  tool_panel_section_label: 'bam_sam_manipulation'

# biom_manipulation
- name: 'suite_biom_format'
  owner: 'iuc'
  tool_panel_section_label: 'biom_manipulation'

# assembly
- name: 'fastq_paired_end_joiner'
  owner: 'devteam'
  tool_panel_section_label: 'assembly'

- name: 'fastq_join'
  owner: 'lparsons'
  tool_panel_section_label: 'assembly'

# quality_control
- name: 'fastqc'
  owner: 'devteam'
  tool_panel_section_label: 'quality_control'

- name: 'prinseq'
  owner: 'iuc'
  tool_panel_section_label: 'quality_control'

- name: 'trim_galore'
  owner: 'bgruening'
  tool_panel_section_label: 'quality_control'

- name: 'trimmomatic'
  owner: 'pjbriggs'
  tool_panel_section_label: 'quality_control'

- name: 'multiqc'
  owner: 'engineson'
  tool_panel_section_label: 'quality_control'

# clustering
- name: 'cdhit'
  owner: 'bebatut'
  tool_panel_section_label: 'clustering'

- name: 'format_cd_hit_output'
  owner: 'bebatut'
  tool_panel_section_label: 'clustering'

# sorting
- name: 'sortmerna'
  owner: 'rnateam'
  tool_panel_section_label: 'sorting'

- name: 'data_manager_sortmerna_database_downloader'
  owner: 'rnateam'
  tool_panel_section_label: 'sorting'

# similarity_search
- name: 'ncbi_blast_plus'
  owner: 'devteam'
  tool_panel_section_label: 'similarity_search'

- name: 'diamond'
  owner: 'bgruening'
  tool_panel_section_label: 'similarity_search'

# mapping
- name: 'bwa'
  owner: 'devteam'
  tool_panel_section_label: 'mapping'

- name: 'bowtie2'
  owner: 'devteam'
  tool_panel_section_label: 'mapping'

# alignment
- name: 'hmmer3'
  owner: 'iuc'
  tool_panel_section_label: 'alignment'
