---

api_key: admin
galaxy_instance: http://localhost:8080
tools:

# metabolism_assignation
- name: 'suite_humann2'
  owner: 'iuc'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'group_humann2_uniref_abundances_to_go'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'compare_humann2_output'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'interproscan5'
  owner: 'bgruening'
  install_resolver_dependencies: False
  tool_panel_section_label: 'metabolism_assignation'

- name: 'suite_picrust'
  owner: 'iuc'
  tool_panel_section_label: 'metabolism_assignation'

# combination_taxo_func
- name: 'combine_metaphlan2_humann2'
  owner: 'bebatut'
  tool_panel_section_label: 'combination_taxo_func'
