---

api_key: admin
galaxy_instance: http://localhost:8080
tools:

# data_retrieval
- name: 'suite_ebi_tools'
  owner: 'iuc'
  tool_panel_section_label: 'data_retrieval'

# text_manipulation 
- name: 'add_value'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'change_case'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'column_join'
  owner: 'jjohnson'
  tool_panel_section_label: 'text_manipulation'

- name: 'collection_column_join'
  owner: 'iuc'
  tool_panel_section_label: 'text_manipulation'

- name: 'column_maker'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'concatenate_multiple_datasets'
  owner: 'mvdbeek'
  tool_panel_section_label: 'text_manipulation'

- name: 'convert_characters'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'cut_columns'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'merge_cols'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'regex_find_replace'
  owner: 'galaxyp'
  tool_panel_section_label: 'text_manipulation'

- name: 'remove_beginning'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'show_beginning'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'show_tail'
  owner: 'devteam'
  tool_panel_section_label: 'text_manipulation'

- name: 'split_file_on_column'
  owner: 'bgruening'
  tool_panel_section_label: 'text_manipulation'

- name: 'unique'
  owner: 'bgruening'
  tool_panel_section_label: 'text_manipulation'

- name: 'normalize_dataset'
  owner: 'bebatut'
  tool_panel_section_label: 'text_manipulation'

- name: 'extract_min_max_lines'
  owner: 'bebatut'
  tool_panel_section_label: 'text_manipulation'

# seq_manipulation 
- name: 'seq_filter_by_id'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'seq_rename'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'seq_select_by_id'
  owner: 'peterjc'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fastq_to_fasta'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fasta_to_tabular'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'split_paired_reads'
  owner: 'devteam'
  tool_panel_section_label: 'seq_manipulation'

- name: 'convert_extract_sequence_file'
  owner: 'bebatut'
  tool_panel_section_label: 'seq_manipulation'

- name: 'fasta_add_barcode'
  owner: 'bebatut'
  tool_panel_section_label: 'seq_manipulation'

# bam_sam_manipulation
- name: 'suite_samtools_1_2'
  owner: 'devteam'
  tool_panel_section_label: 'bam_sam_manipulation'

# biom_manipulation
- name: 'suite_biom_format'
  owner: 'iuc'
  tool_panel_section_label: 'biom_manipulation'

# assembly
- name: 'fastq_paired_end_joiner'
  owner: 'devteam'
  tool_panel_section_label: 'assembly'

- name: 'fastq_join'
  owner: 'lparsons'
  tool_panel_section_label: 'assembly'

# quality_control
- name: 'fastqc'
  owner: 'devteam'
  tool_panel_section_label: 'quality_control'

- name: 'prinseq'
  owner: 'iuc'
  tool_panel_section_label: 'quality_control'

- name: 'trim_galore'
  owner: 'bgruening'
  tool_panel_section_label: 'quality_control'

- name: 'trimmomatic'
  owner: 'pjbriggs'
  tool_panel_section_label: 'quality_control'

# clustering
- name: 'cdhit'
  owner: 'bebatut'
  tool_panel_section_label: 'clustering'

- name: 'format_cd_hit_output'
  owner: 'bebatut'
  tool_panel_section_label: 'clustering'

# sorting
- name: 'sortmerna'
  owner: 'rnateam'
  tool_panel_section_label: 'sorting'

- name: 'data_manager_sortmerna_database_downloader'
  owner: 'rnateam'
  tool_panel_section_label: 'sorting'

# similarity_search
- name: 'ncbi_blast_plus'
  owner: 'devteam'
  tool_panel_section_label: 'similarity_search'

- name: 'diamond'
  owner: 'bgruening'
  tool_panel_section_label: 'similarity_search'

# mapping
- name: 'bwa'
  owner: 'devteam'
  tool_panel_section_label: 'mapping'

- name: 'bowtie2'
  owner: 'devteam'
  tool_panel_section_label: 'mapping'

# alignment
- name: 'hmmer3'
  owner: 'iuc'
  tool_panel_section_label: 'alignment'

# metagenomics_manipulation
- name: 'vsearch'
  owner: 'iuc'
  tool_panel_section_label: 'metagenomics_manipulation'

# amplicon_sequence_processing
- name: 'suite_mothur'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'suite_qiime'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'data_manager_qiime_database_downloader'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

# wgs_taxonomic_assignations
- name: 'suite_metaphlan2'
  owner: 'iuc'
  tool_panel_section_label: 'wgs_taxonomic_assignations'

- name: 'format_metaphlan2_output'
  owner: 'bebatut'
  tool_panel_section_label: 'wgs_taxonomic_assignations'

- name: 'suite_kraken_0_10_5'
  owner: 'devteam'
  tool_panel_section_label: 'wgs_taxonomic_assignations'

# metabolism_assignation
- name: 'suite_humann2'
  owner: 'iuc'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'group_humann2_uniref_abundances_to_go'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'compare_humann2_output'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'interproscan5'
  owner: 'bgruening'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'suite_picrust'
  owner: 'iuc'
  tool_panel_section_label: 'metabolism_assignation'

# combination_taxo_func
- name: 'combine_metaphlan2_humann2'
  owner: 'bebatut'
  tool_panel_section_label: 'combination_taxo_func'

# visualization
- name: 'export2graphlan'
  owner: 'iuc'
  tool_panel_section_label: 'visualization'

- name: 'suite_graphlan'
  owner: 'iuc'
  tool_panel_section_label: 'visualization'

- name: 'taxonomy_krona_chart'
  owner: 'crs4'
  tool_panel_section_label: 'visualization'