---

api_key: admin
galaxy_instance: http://localhost:8080
install_resolver_dependencies: true
install_tool_dependencies: false
tools:

# metabolism_assignation
- name: 'suite_humann2'
  owner: 'iuc'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'group_humann2_uniref_abundances_to_go'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'

- name: 'compare_humann2_output'
  owner: 'bebatut'
  tool_panel_section_label: 'metabolism_assignation'
  install_resolver_dependencies: false
