---

api_key: admin
galaxy_instance: http://localhost:8080
tools:

# amplicon_sequence_processing
- name: 'suite_mothur'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'suite_qiime'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'data_manager_qiime_database_downloader'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

# metagenomics_manipulation
- name: 'vsearch'
  owner: 'iuc'
  tool_panel_section_label: 'metagenomics_manipulation'

- name: 'nonpareil'
  owner: 'iuc'
  tool_panel_section_label: 'metagenomics_manipulation'

# assembly
- name: 'megahit'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

- name: 'metaspades'
  owner: 'nml'
  tool_panel_section_label: 'assembly'

- name: 'quast'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

- name: 'valet'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

# wgs_taxonomic_assignations
- name: 'suite_metaphlan2'
  owner: 'iuc'
  tool_panel_section_label: 'wgs_taxonomic_assignations'

- name: 'format_metaphlan2_output'
  owner: 'bebatut'
  tool_panel_section_label: 'wgs_taxonomic_assignations'

- name: 'suite_kraken_0_10_5'
  owner: 'devteam'
  tool_panel_section_label: 'wgs_taxonomic_assignations'
