---

api_key: admin
galaxy_instance: http://localhost:8080
tools:
# metagenomics_manipulation
- name: 'vsearch'
  owner: 'iuc'
  tool_panel_section_label: 'metagenomics_manipulation'

- name: 'nonpareil'
  owner: 'iuc'
  tool_panel_section_label: 'metagenomics_manipulation'

# metagenomics_manipulation
- name: 'megahit'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

- name: 'metaspades'
  owner: 'nml'
  tool_panel_section_label: 'assembly'

- name: 'quast'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

- name: 'valet'
  owner: 'iuc'
  tool_panel_section_label: 'assembly'

# amplicon_sequence_processing
- name: 'suite_mothur'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'suite_qiime'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'

- name: 'data_manager_qiime_database_downloader'
  owner: 'iuc'
  tool_panel_section_label: 'amplicon_sequence_processing'
