data_managers:

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan2_database_downloader/data_manager_metaphlan2_download/2.6.0
      # MetaPhlAn2 database
      params:
        - 'database': '{{ item }}'
      items:
        - db_v20
      data_table_reload:
        - metaphlan2_database

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Nucleotide database: full chocophlan
      params:
        - 'db|database': 'chocophlan'
        - 'db|build': '{{ item }}'
      items:
        - full
      data_table_reload:
        - humann2_nucleotide_database

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Protein database: full uniref90
      params:
        - 'db|database': 'uniref'
        - 'db|build': '{{ item }}'
      items:
        - uniref
      data_table_reload:
        - humann2_protein_database

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Protein database: full uniref50
      params:
        - 'db|database': 'uniref'
        - 'db|build': '{{ item }}'
      items:
        - uniref50_diamond
      data_table_reload:
        - humann2_protein_database

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_qiime_database_downloader/data_manager_qiime_download/1.9.1
      # HUMAnN2 database: Protein database: full uniref50
      params:
        - 'db|database': 'greengenes'
        - 'db|version': '{{ item }}'
      items:
        - '13_8'
      data_table_reload:
        - qiime_rep_set
        - qiime_rep_set_aligned
        - qiime_taxonomy
        - qiime_trees

    - id: toolshed.g2.bx.psu.edu/repos/rnateam/data_manager_sortmerna_database_downloader/data_manager_sortmerna_download/2.1b.0
      params:
      items:
      data_table_reload:
        - rRNA_databases

