data_managers:

    - id: toolshed.g2.bx.psu.edu/repos/iuc/data_manager_metaphlan2_database_downloader/data_manager_metaphlan2_download/2.6.0
      # MetaPhlAn2 database
      params:
        - 'database': 'db_v20'
      data_table_reload:
        - metaphlan2_database

    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Nucleotide database: full chocophlan
      params:
        - 'database': 'chocophlan'
        - 'build': 'full'
      data_table_reload:
        - humann2_nucleotide_database

    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Protein database: full uniref90
      params:
        - 'database': 'uniref'
        - 'build': 'uniref'
      data_table_reload:
        - humann2_protein_database

    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_humann2_database_downloader/data_manager_humann2_download/0.9.9
      # HUMAnN2 database: Protein database: full uniref50
      params:
        - 'database': 'uniref'
        - 'build': 'uniref50_diamond'
      data_table_reload:
        - humann2_protein_database
  
    - id: toolshed.g2.bx.psu.edu/repos/devteam/data_manager_qiime_database_downloader/data_manager_qiime_download/0.9.9
      # HUMAnN2 database: Protein database: full uniref50
      params:
        - 'database': 'greengenes'
        - 'build': '13_8'
      data_table_reload:
        - qiime_rep_set
        - qiime_rep_set_aligned
        - qiime_taxonomy
        - qiime_trees
