lib_dir: lib
local_galaxy_dir: galaxy-master
galaxy_dir: $lib_dir/$local_galaxy_dir
galaxy_tool_dir: $galaxy_dir/tools/
tool_dir: $lib_dir/galaxy_tools/
tool_playbook: $lib_dir/galaxy-tools-playbook/
data_dir: data
db_dir: $data_dir/db/

master_api_key: "8a099e97b0a83c73ead9f5b0fe19f4be"
port: "8181"
host: "127.0.0.1"
admin_users: "asaim-admin@asaim.com"