lib_dir: lib
local_galaxy_dir: galaxy-master
galaxy_dir: $lib_dir/$local_galaxy_dir
galaxy_tool_dir: $galaxy_dir/tools/
tool_dir: $lib_dir/galaxy_tools/
tool_playbook_dir: $lib_dir/galaxy_tools_playbook/
shed_dir: $lib_dir/shed_tools/

data_dir: data
galaxy_conf_file_dir: $data_dir/galaxy_config/
tool_data_dir: $data_dir/tool-data
tool_playbook_files_dir: $data_dir/galaxy_tools_playbook/

db_dir: $data_dir/db/

master_api_key: "8a099e97b0a83c73ead9f5b0fe19f4be"
port: "8080"
host: "0.0.0.0"
admin_users: "asaim-admin@asaim.com"